TARGET=synth
OBJECTS=jackclient.o Buffer.o synthinit.o Osc.o System.o SoundProcessor.o alsamidi.o Voice.o VoiceManager.o
LDFLAGS=-ljack -lasound
CFLAGS=-g

.cpp.o:
	g++ -c $? $(CFLAGS)

$(TARGET):$(OBJECTS) synth_ui.h
	g++ -o $@ $(OBJECTS) $(LDFLAGS)

synth_ui.h: synth.ui
	uic synth.ui > synth_ui.h

clean:
	rm -f *.o $(TARGET)

cycle: clean install

